language: cpp

compiler: gcc
dist: bionic

branches:
  only:
    - master
    - develop

install:
  - sudo apt-get install -y g++ pkg-config scons ragel gengetopt libuv1-dev libunwind-dev libpulse-dev libsox-dev libcpputest-dev libtool intltool autoconf automake make cmake

before_script:
  - git clone --single-branch --branch "${TRAVIS_BRANCH}" https://github.com/roc-streaming/roc-toolkit.git
  - scons -C roc-toolkit -Q --compiler=gcc --build-3rdparty=openfec
  - sudo scons -C roc-toolkit -Q --compiler=gcc --build-3rdparty=openfec install

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - test -e ../bin/rt-tests

after_failure:
  - cat googletest-prefix/src/googletest-stamp/googletest-build-*.log
